Adds .adoc extension support
oasp/asciidoc-link-checker pull request #5
Opened 2017-09-07 00:53 UTC by gaurav-nelson

Addes support for `.adoc` file extension for asciidoc files. [Asciidoctor](https://github.com/asciidoctor/asciidoctor) uses `.adoc` extension.

Test Output:
```bash
npm test

> @oasp/asciidoc-link-checker@1.1.2 test /home/user/asciidoc-link-checker
> mocha --opts mocha.opts

  fixLink function
    ✓ should return true

  getLinkValue function
    ✓ should return https://www.google.es

  getImageValue function
    ✓ should return true true true true

  sendRequest  function
    ✓ should return true (431ms)

  sendRequest  function
 undefined ---> http://dilbert.com/404 ---> 404
    ✓ should return false (575ms)

  5 passing (1s)

```

2017-09-07 00:59 UTC, gaurav-nelson commented
1. Updated `constants.ts`
2. Ran 'npm run build'
3. Commit

2017-09-08 00:00 UTC, gaurav-nelson commented
Resolved merge conflicts and rebased.

2017-09-08 09:19 UTC, maybeec requested changes

2017-09-08 09:19 UTC, maybeec commented on src/constants.ts
> +    public static readonly adoc: string = ".{.asciidoc,adoc}";
Just looking at the change, there is one dot too much within the brackets, isn't it?

2017-09-08 11:54 UTC, gaurav-nelson commented
Sorry about that, fixed it in the latest commit.

2017-09-08 12:05 UTC, maybeec approved these changes

2017-09-08 12:06 UTC, merged